import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",// useful when you want to provide a fallback title for child route segments they don't explicity specify a title
    template:"%s | Code Evolution", //to create dynamic titles by adding a prefix, apply to child or segments and not the segment which it is defined
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          className="bg-red-500"
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
